version: '3.7'
services:

  # Memcache
  memcache:
    image: memcached:1.5.12

  # CONSUL
  app:
    image: mysocietyorg/consul:${TAG:-latest}
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    working_dir: /var/www/consul
    volumes:
      - ./config/secrets.yml.deploy:/var/www/consul/config/secrets.yml:ro
      - ./config/database.yml.deploy:/var/www/consul/config/database.yml:ro
      - ./config/application_custom.rb:/var/www/consul/config/application_custom.rb:ro
      - ./config/environments/${RAILS_ENV:-production}.rb.deploy:/var/www/consul/config/environments/${RAILS_ENV:-production}.rb:ro
      - ./log:/var/www/consul/log
      - consul-system:/var/www/consul/public/system
    environment:
      MEMCACHE_SERVERS: "memcache:11211"
      RAILS_ENV: "${RAILS_ENV:-production}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-consul_development}"
      POSTGRES_HOST: "${POSTGRES_HOST:-database}"
      SERVER_NAME: "${SERVER_NAME:-consul.127.0.0.1.nip.io}"
      RAILS_SERVE_STATIC_FILES: "true"
      NEW_RELIC_AGENT_ENABLED: "false"
      CONFIG_FORCE_SSL: "${CONFIG_FORCE_SSL:-true}"
      CONFIG_SMTP_ENABLE: "${CONFIG_SMTP_ENABLE}"
      CONFIG_SMTP_ADDRESS: "${CONFIG_SMTP_ADDRESS:-smtp.mysociety.org}"
      CONFIG_SMTP_PORT: "${CONFIG_SMTP_PORT:-25}"
      CONFIG_SMTP_USERNAME: "${CONFIG_SMTP_USERNAME}"
      CONFIG_SMTP_PASSWORD: "${CONFIG_SMTP_PASSWORD}"
      CONFIG_SMTP_DOMAIN: "${CONFIG_SMTP_HELO:-localhost}"
    depends_on:
      - memcache
    ports:
      - "${PORT:-3000}:3000"

volumes:
  consul-system:
